name: 🚀 KSU-8937

on:
  workflow_dispatch:

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: KSU-8937

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 📦 Install Dependencies
        run: |
          echo "🧰 Installing required packages..."
          sudo apt update
          sudo apt install -y git bison flex libxml2 libssl-dev bc zip default-jre python3 python3-pip wget curl aria2 cpio bash ccache jq \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libncurses-dev
          echo "✅ Dependencies installed successfully!"

      - name: 💾 Cache ccache
        uses: actions/cache@v3
        with:
          path: /tmp/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: 🛠️ Build Kernel
        env:
          TELEGRAM_CHAT_ID: -1002287610863
          TELEGRAM_BOT_TOKEN: 7868194496:AAGY7WwRRbeCOPYOnczoCPh2psC43Q0F3JI
          KERNEL_SOURCE: https://github.com/AzyrRuthless/kernel_msm-4.19
          KERNEL_BRANCH: mithorium/a13/master
        run: |
          echo "🚀 Starting the kernel build process..."
          chmod +x 8937v2.sh
          ./8937v2.sh
          echo "🎉 Kernel build completed!"
          
